script: 'bundle exec rake test'
language: ruby
rvm:
  - 1.9.3
  - 2.0.0

gemfile:
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/3.1.gemfile
